name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Run ci
      run: npm ci
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Run tests
      run: npm run test
    - name: Vercel Pull Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    - name: Vercel Build Project
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
    - name: Vercel Deploy Artifacts
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
