name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Run ci
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Run build
      run: npm run build
    - name: Deploy no Vercel
      run: |
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
